################################################################################
# C H A M E L E O N   Project makefile                                         #
################################################################################
# Copyright (C) 2001-2003 Soundart                                             #
# www.soundart-hot.com                                                         #
# support@soundart-hot.com                                                     #
################################################################################

include /Chameleon.sdk/make/common.mak

common:
	@$(MAKE) $(MAKECMDGOALS) -r -R -s -C ..
